 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'europe-west1-docker.pkg.dev/first-project-305113/converters-docker-repo/json-converter-api:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'europe-west1-docker.pkg.dev/first-project-305113/converters-docker-repo/json-converter-api:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'geodat-converter'
   - '--image'
   - 'europe-west1-docker.pkg.dev/first-project-305113/converters-docker-repo/json-converter-api:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
   - '--set-env-vars'
   - '[APIKEY=RWAecgRF90I2CJf,NODE_ENV=development]'
   - '--concurrency'
   - '4'
   - '--max-instances'
   - '15'
   - '--allow-unauthenticated'
   - '--platform'
   - 'managed'
 images:
 - 'europe-west1-docker.pkg.dev/first-project-305113/converters-docker-repo/json-converter-api:$COMMIT_SHA'